### ISSUE TITLE
missing apache launch guide

### ISSUE THREAD

**Issue by tofr** [LargeLlama/Miami-Ultras#3]
Launch instructions
Use appropriate formatting to denote commands, etc.
Include at least these 2 flavors of install guide, named as shown:
"Install and run on localhost"
"Install and run on Apache2"

**Comment by LargeLlama** [comment]
Fixed readme, repository structure to soon follow with appropriate branches, as discussed in class

Master branch will contain Apache-ready files and directory structure
Dev branch will contain Flask-ready files and directory structure
